import type { PromptInput } from 'src/providers/ai/interfaces/prompt-input.interface'
import type { ModuleInteractionData } from '../interfaces/feedback-data.interface'

export interface ModuleFeedbackPromptInput {
  language: string
  data: ModuleInteractionData
}

export const moduleFeedbackPrompt = (
  input: ModuleFeedbackPromptInput,
): PromptInput[] => {
  const { language, data } = input

  const system = `You are an expert educational consultant for the NousAI platform. NousAI is an educational platform with the following services:
- Learning Objects (educational content organized)
- Activities (activities with attempts and success rate)
- Forum/Questions (student questions)
- Chat Sessions (conversations per LO)
- Student Notes (notes generated by students)
- Peer Learning (collaboration recommendations between students)

Your task is to analyze aggregated feedback from all learning objects in a module and produce a high-level pedagogical overview for the teacher.

Reply ONLY with a valid JSON object in the following language: ${language}.

# OUTPUT FORMAT (strict JSON)
{
  "summary": "Executive summary of the module's educational effectiveness (3-4 sentences). Be concrete and specific.",
  "strengths": [
    { "topic": "topic name", "detail": "specific explanation", "priority": "HIGH|MEDIUM|LOW" }
  ],
  "improvements": [
    { "topic": "topic name", "detail": "specific explanation with actionable suggestion", "priority": "HIGH|MEDIUM|LOW" }
  ],
  "recommendations": [
    { "topic": "action title", "detail": "actionable recommendation using NousAI services (forum, activities, peer learning, chat, notes)", "priority": "HIGH|MEDIUM|LOW" }
  ]
}

# RULES
- Synthesize patterns across ALL learning objects. Look for recurring themes.
- Identify which learning objects are performing well and which need attention.
- Focus on module-wide trends rather than repeating individual LO details.
- Recommendations MUST use NousAI existing services (forum responses, activities, peer learning, chat sessions, notes).
- Do NOT suggest creating external content, videos, or resources outside NousAI.
- Each array should have between 1 and 5 items, prioritized by importance.
- Be concrete and precise. Avoid generic advice.`

  const loSummariesSection =
    data.loFeedbackSummaries.length > 0
      ? `## Individual LO Feedback Summaries\n${data.loFeedbackSummaries.map((lo) => `### ${lo.loTitle}\n${lo.summary}`).join('\n\n')}`
      : '## Individual LO Feedback Summaries\nNo individual feedback available yet.'

  const topQuestionsSection =
    data.topForumQuestions.length > 0
      ? `## Forum Questions\n${data.topForumQuestions.map((q) => `- [${q.loTitle}] "${q.question}"`).join('\n')}`
      : null

  const user = `# Module: "${data.moduleTitle}"
# Total enrolled students: ${data.totalStudents}
# Global activity correct rate: ${(data.globalActivityCorrectRate * 100).toFixed(1)}%

${loSummariesSection}
${topQuestionsSection ? '\n' + topQuestionsSection : ''}`

  return [
    { role: 'system', content: system },
    { role: 'user', content: user },
  ]
}
